### ISSUE TITLE
[DOCS:]: microcontroller vs. microprocessor

### ISSUE THREAD

**Issue by YS-McGee** [PerytonSpace/stag-1#1]
### Topic [REQUIRED]

difference between microcontroller and microprocessor

### Reasoning [REQUIRED]

In the README it says "Stag-1 is ... based around the RP2040 microprocessor. But actually RP2040 is a microcontroller instead of a microprocessor. "a microcontroller (MCU) typically includes a processor core, memory, and peripherals all integrated on a single chip, designed for embedded systems. A microprocessor, on the other hand, usually refers to just the central processing unit (CPU) without integrated memory or peripherals." from ChatGPT. A microprocessor would be such as the Intel Core i9, Apple M1; and microcontroller would be such as ESP32, STM32F103.

**Comment by Harveyn4444** [comment]
Updated the README to reflect this
